# Generated by Django 4.2.7 on 2023-11-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_at', models.DateTimeField(auto_now=True, verbose_name='Date and time when webhook responded')),
                ('response_content', models.TextField(verbose_name='Response JSON')),
            ],
        ),
    ]
