# Generated by Django 4.2.7 on 2023-11-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Telegram bot name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Telegram bot description')),
                ('API_token', models.CharField(max_length=50, unique=True, verbose_name='Telegram bot API token')),
                ('secret_token_hash', models.CharField(max_length=64, unique=True, verbose_name='Bot webhook hashed token')),
            ],
            options={
                'verbose_name': 'Registered bot',
                'verbose_name_plural': 'Registered bots',
            },
        ),
        migrations.AlterModelOptions(
            name='webhookresponse',
            options={'verbose_name': 'Webhook response', 'verbose_name_plural': 'Webhook responses'},
        ),
    ]
